//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPM_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPM_Users()
        {
            this.Class_Assignements = new HashSet<Class_Assignements>();
            this.Project_Assignments = new HashSet<Project_Assignments>();
            this.Test_Assignments = new HashSet<Test_Assignments>();
        }
    
        public int id { get; set; }
        public int fk_schools { get; set; }
        public Nullable<int> fk_programs { get; set; }
        public string users_name { get; set; }
        public string pass { get; set; }
        public string email { get; set; }
        public bool is_student { get; set; }
        public bool is_teacher { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public byte[] last_login_at { get; set; }
        public Nullable<bool> email_confirmed { get; set; }
        public Nullable<double> gpa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Assignements> Class_Assignements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Assignments> Project_Assignments { get; set; }
        public virtual School School { get; set; }
        public virtual School School1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Assignments> Test_Assignments { get; set; }
    }
}
